# I cannot make portable code in visual studio. Even though I used it for various tests.
# The visual studio project is in Fhdawn/. If you want, Try it. It doesn't work well.
win:
	gcc main.c sys.c connect.c fhdawn.c network.c MemoryModule.c -o win.exe -lws2_32 -static -liphlpapi